// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQKYVFjGvqXz6qvDuXfjfH9C3kq43ul0k',
    appId: '1:210907123493:android:229ae1b3b7923906c1d4cc',
    messagingSenderId: '210907123493',
    projectId: 'random-jokes-6b8dd',
    storageBucket: 'random-jokes-6b8dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzHwFU0ZpL5aGmvSQH4EzB0QQeZ9tBrI',
    appId: '1:210907123493:ios:104f29a97eea6b87c1d4cc',
    messagingSenderId: '210907123493',
    projectId: 'random-jokes-6b8dd',
    storageBucket: 'random-jokes-6b8dd.appspot.com',
    iosBundleId: 'com.example.randomJokes.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdzHwFU0ZpL5aGmvSQH4EzB0QQeZ9tBrI',
    appId: '1:210907123493:ios:cfc8cbe6c7fffddac1d4cc',
    messagingSenderId: '210907123493',
    projectId: 'random-jokes-6b8dd',
    storageBucket: 'random-jokes-6b8dd.appspot.com',
    iosBundleId: 'com.example.randomJokes.RunnerTests',
  );
}
