name: random_jokes
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  get_it: ^7.6.4
  domain:
    path: domain
  common:
    path: common
  data:
    path: data
  home:
    path: features/home
  injectable: ^2.3.0
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/translation/
